import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductServiceService {
  list: Product[] =
    [
      { "id": 1, "catId": 100, "name": "Dahlbom", "description": "Mosciski-West", "image": "Aerified", "price": 9613, "salePrice": 4568, "stock": "Becton, Dickinson and Company", "featured": true, "active": true },
      { "id": 2, "catId": 100, "name": "Jeanneau", "description": "Sporer-Mitchell", "image": "Alpha", "price": 9614, "salePrice": 4569, "stock": "DENTSPLY SIRONA Inc.", "featured": false, "active": false },
      { "id": 3, "catId": 100, "name": "Fadell", "description": "Mante-Jakubowski", "image": "Tresom", "price": 9615, "salePrice": 4570, "stock": "AveXis, Inc.", "featured": false, "active": true },
      { "id": 4, "catId": 100, "name": "Elnough", "description": "Bahringer Inc", "image": "Temp", "price": 9616, "salePrice": 4571, "stock": "National Research Corporation", "featured": false, "active": false },
      { "id": 5, "catId": 100, "name": "Putman", "description": "Towne, Trantow and O'Reilly", "image": "Job", "price": 9617, "salePrice": 4572, "stock": "Solar Capital Ltd.", "featured": true, "active": false },
      { "id": 6, "catId": 100, "name": "Bram", "description": "Robel Inc", "image": "Keylex", "price": 9618, "salePrice": 4573, "stock": "PowerShares Nasdaq Internet Portfolio", "featured": false, "active": true },
      { "id": 7, "catId": 100, "name": "Bradtke", "description": "Bogan, Crist and Boyle", "image": "Fixflex", "price": 9619, "salePrice": 4574, "stock": "TCW Strategic Income Fund, Inc.", "featured": true, "active": false },
      { "id": 8, "catId": 100, "name": "Bird", "description": "Cormier LLC", "image": "Asoka", "price": 9620, "salePrice": 4575, "stock": "Wintrust Financial Corporation", "featured": false, "active": false },
      { "id": 9, "catId": 100, "name": "Rodge", "description": "Gaylord-Kuphal", "image": "Job", "price": 9621, "salePrice": 4576, "stock": "Anworth Mortgage Asset  Corporation", "featured": true, "active": true },
      { "id": 10, "catId": 100, "name": "Milroy", "description": "Legros-Rempel", "image": "Tin", "price": 9622, "salePrice": 4577, "stock": "Gentex Corporation", "featured": true, "active": false },
      { "id": 11, "catId": 100, "name": "Enrique", "description": "Jakubowski-Zulauf", "image": "Holdlamis", "price": 9623, "salePrice": 4578, "stock": "Capital City Bank Group", "featured": true, "active": false },
      { "id": 12, "catId": 100, "name": "Rigler", "description": "Wintheiser, Schimmel and Carter", "image": "Bigtax", "price": 9624, "salePrice": 4579, "stock": "Harley-Davidson, Inc.", "featured": false, "active": false },
      { "id": 13, "catId": 100, "name": "McKnish", "description": "Boyer, Powlowski and Ward", "image": "Duobam", "price": 9625, "salePrice": 4580, "stock": "Valley National Bancorp", "featured": false, "active": false },
      { "id": 14, "catId": 100, "name": "Poter", "description": "Ritchie, Mayert and Stokes", "image": "Konklux", "price": 9626, "salePrice": 4581, "stock": "CMS Energy Corporation", "featured": true, "active": false },
      { "id": 15, "catId": 100, "name": "Songer", "description": "Zieme-Gusikowski", "image": "Sub-Ex", "price": 9627, "salePrice": 4582, "stock": "Perrigo Company", "featured": false, "active": true },
      { "id": 16, "catId": 100, "name": "Arling", "description": "Stark, Rogahn and Cassin", "image": "Regrant", "price": 9628, "salePrice": 4583, "stock": "iShares 20+ Year Treasury Bond ETF", "featured": false, "active": false },
      { "id": 17, "catId": 100, "name": "Southern", "description": "Reichel-Harvey", "image": "Otcom", "price": 9629, "salePrice": 4584, "stock": "Comp En De Mn Cemig ADS", "featured": true, "active": false },
      { "id": 18, "catId": 100, "name": "Twigge", "description": "Gutmann-Lesch", "image": "Toughjoyfax", "price": 9630, "salePrice": 4585, "stock": "VictoryShares US Small Cap Volatility Wtd ETF", "featured": true, "active": false },
      { "id": 19, "catId": 100, "name": "Grishelyov", "description": "DuBuque Group", "image": "Cookley", "price": 9631, "salePrice": 4586, "stock": "Gores Holdings II, Inc.", "featured": false, "active": true },
      { "id": 20, "catId": 100, "name": "Maliffe", "description": "Swift-Mayer", "image": "Ventosanzap", "price": 9632, "salePrice": 4587, "stock": "Clearwater Paper Corporation", "featured": false, "active": false },
      { "id": 21, "catId": 100, "name": "Vondruska", "description": "Jacobs-Price", "image": "Latlux", "price": 9633, "salePrice": 4588, "stock": "Prudential Public Limited Company", "featured": false, "active": false },
      { "id": 22, "catId": 100, "name": "Sherred", "description": "Stokes, Gutmann and Roberts", "image": "It", "price": 9634, "salePrice": 4589, "stock": "USA Truck, Inc.", "featured": false, "active": true },
      { "id": 23, "catId": 100, "name": "Gorthy", "description": "Bruen Group", "image": "Tampflex", "price": 9635, "salePrice": 4590, "stock": "Unifirst Corporation", "featured": false, "active": true },
      { "id": 24, "catId": 100, "name": "Plumridge", "description": "Morar-Rau", "image": "Bamity", "price": 9636, "salePrice": 4591, "stock": "Geo Group Inc (The)", "featured": true, "active": true },
      { "id": 25, "catId": 100, "name": "Poundford", "description": "Kertzmann-VonRueden", "image": "Quo Lux", "price": 9637, "salePrice": 4592, "stock": "Elbit Imaging Ltd.", "featured": false, "active": true },
      { "id": 26, "catId": 100, "name": "Campes", "description": "Botsford, Ebert and Kirlin", "image": "Andalax", "price": 9638, "salePrice": 4593, "stock": "Ebix, Inc.", "featured": true, "active": false },
      { "id": 27, "catId": 100, "name": "Deverell", "description": "Dickens-Osinski", "image": "Sonsing", "price": 9639, "salePrice": 4594, "stock": "MB Financial Inc.", "featured": false, "active": false },
      { "id": 28, "catId": 100, "name": "Franiak", "description": "Flatley, Deckow and Kunde", "image": "Regrant", "price": 9640, "salePrice": 4595, "stock": "City Office REIT, Inc.", "featured": false, "active": false },
      { "id": 29, "catId": 100, "name": "Kidsley", "description": "Kertzmann Inc", "image": "Quo Lux", "price": 9641, "salePrice": 4596, "stock": "PGT Innovations, Inc.", "featured": false, "active": true },
      { "id": 30, "catId": 100, "name": "Burchill", "description": "Goldner, Dare and Beatty", "image": "Home Ing", "price": 9642, "salePrice": 4597, "stock": "Monro Muffler Brake, Inc.", "featured": false, "active": true },
      { "id": 31, "catId": 100, "name": "Ghest", "description": "Waters and Sons", "image": "Zontrax", "price": 9643, "salePrice": 4598, "stock": "Central Europe, Russia and Turkey Fund, Inc. (The)", "featured": false, "active": false },
      { "id": 32, "catId": 200, "name": "Stanlake", "description": "Rau, Rice and Fahey", "image": "Zontrax", "price": 9644, "salePrice": 4599, "stock": "DMC Global Inc.", "featured": false, "active": true },
      { "id": 33, "catId": 200, "name": "Wem", "description": "Steuber-Bogan", "image": "Stringtough", "price": 9645, "salePrice": 4600, "stock": "Grupo Aeroportuario Del Pacifico, S.A. de C.V.", "featured": false, "active": true },
      { "id": 34, "catId": 200, "name": "Cureton", "description": "Buckridge-Goodwin", "image": "Otcom", "price": 9646, "salePrice": 4601, "stock": "Universal Health Services, Inc.", "featured": false, "active": true },
      { "id": 35, "catId": 200, "name": "Lett", "description": "O'Connell and Sons", "image": "Toughjoyfax", "price": 9647, "salePrice": 4602, "stock": "Eiger BioPharmaceuticals, Inc.", "featured": false, "active": true },
      { "id": 36, "catId": 200, "name": "Phillis", "description": "Satterfield, Stanton and McClure", "image": "Ventosanzap", "price": 9648, "salePrice": 4603, "stock": "Athene Holding Ltd.", "featured": true, "active": false },
      { "id": 37, "catId": 200, "name": "Cassely", "description": "Cummerata Group", "image": "Aerified", "price": 9649, "salePrice": 4604, "stock": "Public Storage", "featured": false, "active": false },
      { "id": 38, "catId": 200, "name": "Baish", "description": "Daniel-Cartwright", "image": "It", "price": 9650, "salePrice": 4605, "stock": "UMH Properties, Inc.", "featured": false, "active": true },
      { "id": 39, "catId": 200, "name": "Grigolli", "description": "Steuber Group", "image": "Vagram", "price": 9651, "salePrice": 4606, "stock": "Nuveen Select Maturities Municipal Fund", "featured": false, "active": false },
      { "id": 40, "catId": 200, "name": "Cuttell", "description": "Heller and Sons", "image": "Pannier", "price": 9652, "salePrice": 4607, "stock": "Controladora Vuela Compania de Aviacion, S.A.B. de C.V.", "featured": false, "active": false },
      { "id": 41, "catId": 200, "name": "Stailey", "description": "Wiegand Inc", "image": "Home Ing", "price": 9653, "salePrice": 4608, "stock": "PowerShares Optimum Yield Diversified Commodity Strategy No K-", "featured": true, "active": true },
      { "id": 42, "catId": 200, "name": "Robinson", "description": "Becker Inc", "image": "Solarbreeze", "price": 9654, "salePrice": 4609, "stock": "LPL Financial Holdings Inc.", "featured": true, "active": true },
      { "id": 43, "catId": 200, "name": "Fudge", "description": "Fisher Inc", "image": "Fintone", "price": 9655, "salePrice": 4610, "stock": "United Technologies Corporation", "featured": false, "active": false },
      { "id": 44, "catId": 200, "name": "Meo", "description": "Nikolaus-DuBuque", "image": "Biodex", "price": 9656, "salePrice": 4611, "stock": "Associated Capital Group, Inc.", "featured": true, "active": true },
      { "id": 45, "catId": 200, "name": "Clunie", "description": "McClure and Sons", "image": "It", "price": 9657, "salePrice": 4612, "stock": "Tuttle Tactical Management Multi-Strategy Income ETF", "featured": true, "active": false },
      { "id": 46, "catId": 200, "name": "Heeley", "description": "Hegmann, Dooley and Boehm", "image": "Span", "price": 9658, "salePrice": 4613, "stock": "WisdomTree Emerging Markets Quality Dividend Growth Fund", "featured": false, "active": false },
      { "id": 47, "catId": 200, "name": "Deville", "description": "Koss, Turcotte and Huels", "image": "Konklab", "price": 9659, "salePrice": 4614, "stock": "Belden Inc", "featured": false, "active": false },
      { "id": 48, "catId": 200, "name": "Dring", "description": "Nader-Stark", "image": "Keylex", "price": 9660, "salePrice": 4615, "stock": "Incyte Corporation", "featured": true, "active": true },
      { "id": 49, "catId": 200, "name": "Carlsson", "description": "Ritchie-Schumm", "image": "Ronstring", "price": 9661, "salePrice": 4616, "stock": "Halliburton Company", "featured": true, "active": false },
      { "id": 50, "catId": 200, "name": "Cusick", "description": "Cassin Inc", "image": "Latlux", "price": 9662, "salePrice": 4617, "stock": "Brookfield Asset Management Inc", "featured": true, "active": true },
      { "id": 51, "catId": 200, "name": "Caldairou", "description": "Streich, Bruen and Terry", "image": "Alphazap", "price": 9663, "salePrice": 4618, "stock": "Navios Maritime Holdings Inc.", "featured": true, "active": false },
      { "id": 52, "catId": 200, "name": "Fenck", "description": "Nicolas, Lubowitz and Abernathy", "image": "Latlux", "price": 9664, "salePrice": 4619, "stock": "Sequential Brands Group, Inc.", "featured": true, "active": false },
      { "id": 53, "catId": 200, "name": "Parley", "description": "Conroy Group", "image": "Stringtough", "price": 9665, "salePrice": 4620, "stock": "Pacific Gas & Electric Co.", "featured": false, "active": false },
      { "id": 54, "catId": 200, "name": "Vizard", "description": "Kulas, Hyatt and Bernier", "image": "Home Ing", "price": 9666, "salePrice": 4621, "stock": "Atlantic Capital Bancshares, Inc.", "featured": true, "active": true },
      { "id": 55, "catId": 200, "name": "McKeating", "description": "Mitchell, Kozey and Barrows", "image": "Otcom", "price": 9667, "salePrice": 4622, "stock": "Nuveen Build America Bond Opportunity Fund", "featured": false, "active": false },
      { "id": 56, "catId": 200, "name": "Baudins", "description": "Dach Inc", "image": "Aerified", "price": 9668, "salePrice": 4623, "stock": "AppFolio, Inc.", "featured": true, "active": true },
      { "id": 57, "catId": 200, "name": "Angel", "description": "Dickinson-Lang", "image": "Bamity", "price": 9669, "salePrice": 4624, "stock": "Bay Bancorp, Inc.", "featured": true, "active": false },
      { "id": 58, "catId": 200, "name": "Polak", "description": "Bogan Group", "image": "Konklab", "price": 9670, "salePrice": 4625, "stock": "First Trust NASDAQ Smartphone Index Fund", "featured": false, "active": true },
      { "id": 59, "catId": 200, "name": "Betteson", "description": "Bergstrom-Dickinson", "image": "Veribet", "price": 9671, "salePrice": 4626, "stock": "Universal Display Corporation", "featured": true, "active": true },
      { "id": 60, "catId": 200, "name": "Aguilar", "description": "Rohan-Hoeger", "image": "Redhold", "price": 9672, "salePrice": 4627, "stock": "GlycoMimetics, Inc.", "featured": true, "active": false }]

  constructor() { }
}
